# Generated by Django 3.2.9 on 2022-03-04 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fest_app', '0004_auto_20181018_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
